DELETE FROM processes WHERE id > 4;
ALTER TABLE processes AUTO_INCREMENT =1;
DELETE FROM bundles WHERE id > 3;
ALTER TABLE bundles AUTO_INCREMENT =1;
DELETE FROM videos WHERE id > 3;
ALTER TABLE videos AUTO_INCREMENT =1;
DELETE FROM metadata WHERE id > 3;
ALTER TABLE metadata AUTO_INCREMENT =1;



DELETE FROM processes WHERE id > 20;
ALTER TABLE processes AUTO_INCREMENT =1;
DELETE FROM bundles WHERE id > 12;
ALTER TABLE bundles AUTO_INCREMENT =1;
DELETE FROM videos WHERE id > 12;
ALTER TABLE videos AUTO_INCREMENT =1;
DELETE FROM metadata WHERE id > 12;
ALTER TABLE metadata AUTO_INCREMENT =1;